name: Java CI with Gradle & Deploy to Naver cloud

on:
  pull_request:
    branches: [ "master" ]

env:
  docker-container-name: ayu-coupon-service
  docker-image-name: ${{ secrets.DOCKERHUB_USERNAME }}/ayu-coupon-service

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - run: touch ./src/main/resources/application.properties
      - run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties
      - run: cat ./src/main/resources/application.properties

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.docker-image-name }}

      - name: Pull and restart Docker Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            sudo docker stop ${{ env.docker-container-name }}
            sudo docker rmi ${{ env.docker-image-name }}
            sudo docker pull ${{ env.docker-image-name }}
            sudo docker run -d --rm --name ${{ env.docker-container-name }} -v monitoring_data-volume:/pinpoint-agent --net monitoring_pinpoint -p 8080:8080 ${{ env.docker-image-name }}
